// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Gjallarhorn.ReferenceDocumentation")>]
[<assembly: AssemblyProductAttribute("Gjallarhorn")>]
[<assembly: AssemblyDescriptionAttribute("Framework for managing mutable data with change notification and live views")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2017 Reed Copsey, Jr.")>]
[<assembly: AssemblyCompanyAttribute("Reed Copsey, Jr.")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Gjallarhorn.ReferenceDocumentation"
    let [<Literal>] AssemblyProduct = "Gjallarhorn"
    let [<Literal>] AssemblyDescription = "Framework for managing mutable data with change notification and live views"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyCopyright = "Copyright 2017 Reed Copsey, Jr."
    let [<Literal>] AssemblyCompany = "Reed Copsey, Jr."
