// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Gjallarhorn.Bindable")>]
[<assembly: AssemblyProductAttribute("Gjallarhorn")>]
[<assembly: AssemblyDescriptionAttribute("Framework for managing mutable data with change notification and live views")>]
[<assembly: AssemblyVersionAttribute("0.0.10")>]
[<assembly: AssemblyFileVersionAttribute("0.0.10")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2017 Reed Copsey, Jr.")>]
[<assembly: AssemblyCompanyAttribute("Reed Copsey, Jr.")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Gjallarhorn.Bindable"
    let [<Literal>] AssemblyProduct = "Gjallarhorn"
    let [<Literal>] AssemblyDescription = "Framework for managing mutable data with change notification and live views"
    let [<Literal>] AssemblyVersion = "0.0.10"
    let [<Literal>] AssemblyFileVersion = "0.0.10"
    let [<Literal>] AssemblyCopyright = "Copyright 2017 Reed Copsey, Jr."
    let [<Literal>] AssemblyCompany = "Reed Copsey, Jr."
